# Generated by Django 5.2.4 on 2025-07-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loading_point', models.CharField(max_length=100)),
                ('unloading_point', models.CharField(max_length=100)),
                ('truck_type', models.CharField(max_length=100)),
                ('qty', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=100)),
            ],
        ),
    ]
