# Generated by Django 5.2.4 on 2025-07-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirements',
            name='qty',
            field=models.IntegerField(),
        ),
    ]
