# Generated by Django 5.2.4 on 2025-07-27 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_requirements_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_one', models.IntegerField()),
                ('rate_two', models.IntegerField()),
                ('rate_three', models.IntegerField()),
                ('rate_four', models.IntegerField()),
                ('req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.requirements')),
            ],
        ),
    ]
