# Generated by Django 5.2.4 on 2025-07-27 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_bid_req_alter_bid_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='rate_five',
            new_name='rate',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='rate_four',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='rate_one',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='rate_three',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='rate_two',
        ),
    ]
