# Generated by Django 5.2.4 on 2025-08-04 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_bid_req_alter_bid_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirements',
            name='no_of_trucks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
