# Generated by Django 5.2.4 on 2025-08-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_requirements_no_of_trucks'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirements',
            name='drum_type_no_of_drums',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requirements',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirements',
            name='types',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requirements',
            name='weight_per_drum',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
