# Generated by Django 5.2.4 on 2025-08-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_requirements_drum_type_no_of_drums_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirements',
            name='loading_point_full_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirements',
            name='unloading_point_full_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
