# Generated by Django 5.2.4 on 2025-08-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_useraccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_access', models.BooleanField(default=False)),
            ],
        ),
    ]
