# Generated by Django 5.2.5 on 2025-08-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_useraccess_requirement_from_access_alter_bid_req_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccess',
            name='minutes',
            field=models.IntegerField(default=0),
        ),
    ]
