# Generated by Django 5.2.5 on 2025-08-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_useraccess_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccess',
            name='bid_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
