# Generated by Django 5.2.5 on 2025-08-10 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_useraccess_bid_start_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccess',
            old_name='bid_start_time',
            new_name='end_time',
        ),
    ]
