# Generated by Django 5.2.5 on 2025-08-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_rename_bid_start_time_useraccess_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccess',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='useraccess',
            name='minutes',
        ),
        migrations.AddField(
            model_name='generalaccess',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalaccess',
            name='minutes',
            field=models.IntegerField(default=0),
        ),
    ]
