# Generated by Django 5.2.5 on 2025-08-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_bid_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalaccess',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
