# Generated by Django 5.2.5 on 2025-08-15 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_generalaccess_end_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalaccess',
            old_name='end_time',
            new_name='start_time',
        ),
    ]
