# Generated by Django 5.2.4 on 2025-08-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_rename_end_time_generalaccess_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirements',
            name='product',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='truck_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
