# Generated by Django 5.2.4 on 2025-08-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_requirements_product_alter_requirements_qty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirements',
            name='qty',
        ),
        migrations.AddField(
            model_name='requirements',
            name='cel_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
