# Generated by Django 5.2.4 on 2025-08-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_remove_requirements_qty_requirements_cel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirements',
            name='min_dec_val',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
