# Generated by Django 5.2.4 on 2025-08-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_bid_req_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
