# Generated by Django 5.2.4 on 2025-08-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alter_bid_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalaccess',
            name='use_cel',
            field=models.BooleanField(default=True),
        ),
    ]
