# Generated by Django 5.2.4 on 2025-08-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_generalaccess_use_cel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalaccess',
            name='use_cel',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
