# Generated by Django 5.2.4 on 2025-08-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_alter_generalaccess_use_cel'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirements',
            name='approx_mat_mt',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
