# Generated by Django 5.2.4 on 2025-09-15 10:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_requirements_approx_mat_mt'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalaccess',
            name='dec_val_vi',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='rate',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
