# Generated by Django 5.2.4 on 2025-09-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_generalaccess_dec_val_vi_alter_bid_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
