# Generated by Django 5.2.5 on 2025-10-05 14:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_alter_bid_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirements',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
