# Generated by Django 5.2.5 on 2025-10-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_requirements_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirements',
            name='unique_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
