# Generated by Django 5.2.5 on 2025-10-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_alter_requirements_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalaccess',
            name='new_req',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
