# Generated by Django 5.2.5 on 2025-10-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_generalaccess_new_req'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalaccess',
            name='new_req',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
