# Generated by Django 5.2.5 on 2025-10-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_alter_generalaccess_new_req'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalaccess',
            name='interval',
            field=models.IntegerField(default=0),
        ),
    ]
