# Generated by Django 5.2.4 on 2025-10-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_generalaccess_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirements',
            name='req_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
