# Generated by Django 5.2.4 on 2025-10-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_alter_requirements_req_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirements',
            name='req_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
