# Generated by Django 5.2.5 on 2025-10-12 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_alter_requirements_req_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenderedRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rendered_ids', models.IntegerField(blank=True, null=True)),
                ('ga', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.generalaccess')),
            ],
        ),
    ]
