# Generated by Django 5.2.5 on 2025-10-13 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_renderedrequirements'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RenderedRequirements',
        ),
    ]
