# Generated by Django 5.2.4 on 2025-10-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0046_delete_renderedrequirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalaccess',
            name='post_interval_lst',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
