# Generated by Django 5.2.4 on 2025-10-29 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0048_bidmsg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidmsg',
            name='bid',
        ),
    ]
