# Generated by Django 5.2.4 on 2025-10-29 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0049_remove_bidmsg_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidmsg',
            name='req',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='req', to='myapp.requirements'),
        ),
    ]
