# Generated by Django 5.2.4 on 2025-10-30 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0050_bidmsg_req'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidmsg',
            name='bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.bid'),
        ),
    ]
