# Generated by Django 5.2.4 on 2025-10-30 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0051_bidmsg_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidmsg',
            name='bid',
        ),
    ]
