# Generated by Django 5.2.5 on 2026-01-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0054_remove_bidmsg_bid'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(upload_to='landing/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
